/**
* This file was generated by IBM WebSphere Studio Version 3.5
* C:\WDT400\Studio35\BIN\GenerationStyleSheets\V3.5\JSP1.1\ServletModel\DatabaseBean.xsl stylesheet was used to generate this file.
*
* Description - SelectIClient1DBBean
*/ 
package com.overstar.bank.iclient;
// Imports

import com.ibm.db.*;
import com.ibm.webtools.runtime.*;
import java.io.*;
import java.math.*;


// Imports for App Server V3 connection pooling
import javax.sql.DataSource;
import com.ibm.ejs.dbm.jdbcext.*;
import javax.naming.*;
import com.ibm.ejs.ns.jndi.*;
import java.sql.*;
import java.util.*;


// Imports for App Server V3.5 connection pooling
import com.ibm.websphere.advanced.cm.factory.*;



/**  */
 
public class SelectIClient1DBBean extends java.lang.Object 
{

  private static final int NAME_COLUMN = 1; 
  private static final int PARTYID_COLUMN = 2; 

  /** 
  * Instance variable for driver property
  */
  protected java.lang.String driver= "com.ibm.as400.access.AS400JDBCDriver";


  /** 
  * Instance variable for password property
  */
  protected java.lang.String password= "hwodn39fh5";


  /** 
  * Instance variable for SQL statement property
  */
  protected java.lang.String SQLString = "SELECT    QRSDATATST.PARTY.NAME AS NAME,    QRSDATATST.CLIENT.PARTYID AS PARTYID FROM    QRSDATATST.CLIENT,    QRSDATATST.PARTY WHERE    (       (         QRSDATATST.PARTY.PARTYID = QRSDATATST.CLIENT.PARTYID       )      AND     (( QRSDATATST.CLIENT.SERVICEKIND = 1001 ))    ) ORDER BY    NAME";
   

  /** 
  * Instance variable for URL property
  */
  protected java.lang.String URL= "jdbc:as400://dev400.as.net";


  /** 
  * Instance variable for userID property
  */
  protected java.lang.String userID= "ildar";



  /**
  * Variable for the SelectStatement
  */
  protected SelectStatement sqlStatement;
  
  
  /**
  * Variable for the SelectResult - the SQL result set
  */
  protected SelectResult result;
  
  /**
  * Variable to hold the database connection bean
  */
  protected DatabaseConnection connBean = null;
  
  
  /**
  * Variable to hold DataSource
  */
  protected DataSource ds = null;

  /**
  * Variable to hold connection
  */
  protected Connection connection = null;

  /**
  * Variable to hold the data source name from .servlet file
  */
  protected String dataSourceName = "";
  


  /*****************************************************************************
  * Get method for the indexed NAME property
  * @param index The 0 based index of the desired value
  * @return the value of the NAME property at the specified index
  */
  public java.lang.String getNAME(int index)
   throws java.lang.IndexOutOfBoundsException, java.lang.ArrayIndexOutOfBoundsException
  {  
	
	return (java.lang.String) valueAtColumnRow(NAME_COLUMN, index);

  }  

  /*****************************************************************************
  * Get method for the indexed PARTYID property
  * @param index The 0 based index of the desired value
  * @return the value of the PARTYID property at the specified index
  */
  public java.lang.Integer getPARTYID(int index)
   throws java.lang.IndexOutOfBoundsException, java.lang.ArrayIndexOutOfBoundsException
  {  
	
	return (java.lang.Integer) valueAtColumnRow(PARTYID_COLUMN, index);

  }  

  /*****************************************************************************
  * Get method for the driver property
  * @return the value of the driver property
  
  */
  public java.lang.String getDriver(){
	return driver;
  }  
  /*****************************************************************************
  * Set method for the driver property
  * @param value the new value for the driver property
  
  */
  public void setDriver(java.lang.String value){
	this.driver = value;
  }  
  /*****************************************************************************
  * Set method for the password property
  * @param value the new value for the password property
  
  */
  public void setPassword(java.lang.String value){
	this.password = value;
  }  
  /*****************************************************************************
  * Get method for the SQL statement property
  * @return the value of the SQL statement property
  
  */
  public java.lang.String getSQLString(){
	return SQLString;
  }  
  /*****************************************************************************
  * Get method for the URL property
  * @return the value of the URL property
  
  */
  public java.lang.String getURL(){
	return URL;
  }  
  /*****************************************************************************
  * Set method for the URL property
  * @param value the new value for the URL property
  
  */
  public void setURL(java.lang.String value){
	this.URL = value;
  }  
  /*****************************************************************************
  * Get method for the userID property
  * @return the value of the userID property
  
  */
  public java.lang.String getUserID(){
	return userID;
  }  
  /*****************************************************************************
  * Set method for the userID property
  * @param value the new value for the userID property
  
  */
  public void setUserID(java.lang.String value){
	this.userID = value;
  }  

  /*****************************************************************************
  * Get method for the App Server V3 dataSourceName property
  */
  public String getDataSourceName()
  {
	return dataSourceName;
  }  

  /*****************************************************************************
  * Set method for the App Server V3 dataSourceName property
  */
  public void setDataSourceName(String value)
  {
	this.dataSourceName = value;
  }  


  /*****************************************************************************
  * execute action method   * @exception com.ibm.db.DataException
  * @exception java.io.IOException
  * @exception java.lang.Exception

  */
  public void execute()  
   throws com.ibm.db.DataException, java.io.IOException, java.lang.Exception, SQLException, ClassNotFoundException, NoDataException
  {  
	
	initialize();

	// Initialize the parameters for the query
	

	// Execute the SQL statement
	sqlStatement.execute();
	result = sqlStatement.getResult();

	// Selected Empty Result page.
	// If the result set is empty, throw a NoDataException
	try 
	{
	  result.firstRow();
	}
	catch (DataException e)
	{
	  if (e.getErrorCode() == DataException.noResults)
	  {
		closeResultSet();
		NoDataException exception = new NoDataException("Result Set Empty");
		exception.fillInStackTrace();
		throw exception;
	  }
	  else
	  {
		closeResultSet();
		throw e;
	  }
		}

  }  

  /*****************************************************************************
  * Initializes the App Server V3 data acess beans
  * 
  * @exception com.ibm.db.DataException when a database access exception occurs
  * @exception java.io.IOException when an IO error occurs
  */
  protected void initialize() throws DataException, IOException, SQLException, ClassNotFoundException

  {
	StatementMetaData metaData = null;
  
	// Instantiate the connection bean and initialize it
	Class.forName(getDriver());
	connection = DriverManager.getConnection(getURL(), getUserID(), password);
	connBean = new DatabaseConnection(connection);
	

	if (connBean == null)
	{
	  return ;
	}

	// The statement must reference the connection to be used
		sqlStatement = new SelectStatement();
	sqlStatement.setConnection(connBean);

	// Add the SQL string to the metaData
	metaData = sqlStatement.getMetaData();
	metaData.setSQL(getSQLString());

	// Each table the query uses is added to the metadata. Then each column that
	// is returned from the select gets added to the metadata.
	metaData.addTable("QRSDATATST.PARTY");
	metaData.addTable("QRSDATATST.CLIENT");

	metaData.addColumn("NAME", java.lang.String.class, 1);
	metaData.addColumn("PARTYID", java.lang.Integer.class, 4);

	// Create placeholders for the parameters
	
	return;
  }  
   
   
  
  /*****************************************************************************
  * Utility method to get the value at a specific row and column index
  * 
  * @param column the column containing the desired data
  * @param row the row containing the desired data
  * @return the value of the column at the specified row
  * @exception java.lang.ArrayIndexOutOfBoundsException thrown when there is no data at the specified row
  */
  private Object valueAtColumnRow(int column, int row) throws ArrayIndexOutOfBoundsException
  {
	// Index is 0 based but rows are 1 based, so increment the index
	int realRow = row + 1;

	// Handle an empty result set by throwing an exception
	if (result == null)
	{
	  throw new ArrayIndexOutOfBoundsException ("Result set is empty.");
	}

	// Handle an out of bounds index by throwing an exception
	if (realRow > result.getNumRowsInCache())
	{
	  throw new ArrayIndexOutOfBoundsException ("Row is out of bounds.");
	}

	// Adjust the current row to the desired row index
	try 
	{
	  result.setCurrentRow(realRow);
	}
	catch (Exception e)
	{
	  System.out.println("Error occurred in com.ibm.db.SelectResult.setCurrentRow");
	  e.printStackTrace();
	}

	// Return the indexed property element
	try 
	{
	  return result.getColumnValue(column);
	}

	catch (Exception e)
	{
	  System.out.println("Error occurred in com.ibm.db.SelectResult.getColumnValue");
	  e.printStackTrace();
	}
	return null;
  }  
  
  
  /*****************************************************************************
  * Close the result set and release resources
  */
  public void closeResultSet()
  {
	// Release the SQL statement resources
	try 
	{
	  if (result != null)
	  {
		result.close();
		result = null;
	  }
	}
	catch (Exception e)
	{
	  System.out.println("Error occurred in com.ibm.db.SelectResult.close");
	  e.printStackTrace();
	}
	try
	{
	  // Close the App Server V3 connection
	  if (connection != null)
		connection.close();
	}
	catch (Exception e)
	{
	  System.out.println("Error occurred in java.sql.Connection.close");
	  e.printStackTrace();
	}
	return ;
  }   
  
	
  
  /*****************************************************************************
  * Release resources we might be holding when garbage collection occurs.
  */
  protected void finalize() throws Throwable
  {
	closeResultSet();
  }  
   
}